// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLw0MR-tHFO2XjkGazNB5u29x0rfrn4QY',
    appId: '1:566924157760:android:823c30ce3f3d6a4d15d0a5',
    messagingSenderId: '566924157760',
    projectId: 'bluecherry-dvr',
    storageBucket: 'bluecherry-dvr.appspot.com',
    androidClientId:
        '566924157760-9qarhvcpgcd5gtqn40seeouu5qb7prj2.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc2QMZrnlb4jt0IOL0wrjseTufXFI64Dk',
    appId: '1:566924157760:ios:547fdbbd61feb9cd15d0a5',
    messagingSenderId: '566924157760',
    projectId: 'bluecherry-dvr',
    storageBucket: 'bluecherry-dvr.appspot.com',
    iosClientId:
        '566924157760-pmsc8k5344sg3umu0ck30rk7o99cof1o.apps.googleusercontent.com',
    iosBundleId: 'com.bluecherrydvr.bluecherryClient',
  );
}
