name: unity_video_player
description: Video player used in the Unity project
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  unity_video_player_media_kit:
    path: ../unity_video_player_media_kit

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  media_kit:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: 318f3e157e127af84b70d9907d4b30efd50371e6
      path: media_kit/

flutter:
  plugin:
    platforms:
      android:
        default_package: unity_video_player_media_kit
      ios:
        default_package: unity_video_player_media_kit
      macos:
        default_package: unity_video_player_media_kit
      linux:
        default_package: unity_video_player_media_kit
      windows:
        default_package: unity_video_player_media_kit
