name: bluecherry-client
version: 3.0.0-beta7
summary: Bluecherry DVR Client
description: Bluecherry DVR client 

confinement: strict
base: core18
grade: stable

slots:
  dbus-bluecherry-app: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.bluecherry # adjust accordingly to your app name and
    
apps:
  bluecherry-app:
    command: bluecherry_app
    extensions: [flutter-stable] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-bluecherry-app
      
parts:
  mpv:
    source: https://github.com/mpv-player/mpv.git
    plugin: nil

  bluecherry-app:
    source: .
    plugin: flutter
    build-packages:
      - libmpv-dev
      - libmpv1
      - mpv
    stage-packages:
      - libmpv-dev
      - libmpv1
      - mpv
    flutter-target: lib/main.dart # The main entry-point file of the application
