name: bluecherry-client
version: 3.0.0-beta7
summary: Bluecherry DVR Client
description: Bluecherry DVR client 

confinement: strict
base: core18
grade: stable

slots:
  dbus-bluecherry-app: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.bluecherry # adjust accordingly to your app name and
    
apps:
  bluecherry-app:
    command: bluecherry_app
    extensions: [flutter-stable]
    plugs: [wayland, desktop, desktop-legacy, home, audio-playback, pulseaudio, gsettings, opengl, mount-observe, network, network-bind, network-manager, network-observe]
    slots:
      - dbus-bluecherry-app
      
parts:
  bluecherry-app:
    source: .
    plugin: flutter
    build-packages:
      - build-essential
      - software-properties-common
      - pkg-config
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libswscale-dev
      - libmpv-dev
    stage-packages:
      - libmpv1
      - mpv
      - ffmpeg
    flutter-target: lib/main.dart # The main entry-point file of the application

#    build-environment:
#      - CFLAGS: /home/bruno/Documents/paid_projects/fork/unity/mpv/libmpv
#      - CXXFLAGS: /home/bruno/Documents/paid_projects/fork/unity/mpv/libmpv

    # Exclude specific paths from being compiled/included
    override-build: |
      snapcraftctl build
      snapcraftctl exclude **/ephemeral
      snapcraftctl exclude **/plugins
      sed -i '/media_kit_video/d' $SNAPCRAFT_PART_BUILD/CMakeLists.txt
